name: Terraform Checks

on:
  pull_request:
    paths:
      - 'environments/dev/**'
      - 'modules/**'
      - '.github/workflows/terraform.yml'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        working-directory: environments/dev
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: environments/dev
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: environments/dev
        run: terraform validate

  module-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - aks
          - eks
          - gke
          - iam
          - k8s-addons
          - networking
          - storage
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        working-directory: modules/${{ matrix.module }}
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: modules/${{ matrix.module }}
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: modules/${{ matrix.module }}
        run: terraform validate
